# Generated by Django 4.2 on 2023-09-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name_with_house_number', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('home_page', models.URLField(max_length=50)),
            ],
            options={
                'db_table': 'contact_informations',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('profile', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.address')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.contact')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
    ]
