# Generated by Django 4.2 on 2023-09-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(max_length=50),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Programming Language', 'Programming Language'), ('Language', 'Language'), ('Technology', 'Technology'), ('Framework', 'Framework')], default='Programming Language', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('scale', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('Expert', 'Expert')], default='beginner', max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
