# Generated by Django 4.2 on 2023-09-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_contact_email_address_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skills',
        ),
    ]
