# Generated by Django 4.2 on 2023-09-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_rename_skills_skill_alter_skill_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='scale',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Expert')], default=1, max_length=50),
        ),
    ]
