# Generated by Django 4.2 on 2023-11-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
